// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV657QRoPnW2vzyc_Mt92fdLx515-wJHg',
    appId: '1:602344830112:web:903d407a57cd80bc4ec5c5',
    messagingSenderId: '602344830112',
    projectId: 'ombre-event-6d20c',
    authDomain: 'ombre-event-6d20c.firebaseapp.com',
    storageBucket: 'ombre-event-6d20c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcmgW4BY-rgQmyJ7YZKAwQAcfdeZOj27c',
    appId: '1:602344830112:android:db3ca170f5d1264a4ec5c5',
    messagingSenderId: '602344830112',
    projectId: 'ombre-event-6d20c',
    storageBucket: 'ombre-event-6d20c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnPGg5yh2oyY5vn8RarfhzTEP26ETlfUw',
    appId: '1:602344830112:ios:0e22e7c696435cb14ec5c5',
    messagingSenderId: '602344830112',
    projectId: 'ombre-event-6d20c',
    storageBucket: 'ombre-event-6d20c.appspot.com',
    iosClientId:
        '602344830112-k9f86lmvinml06t598u6lpgi5khfpj61.apps.googleusercontent.com',
    iosBundleId: 'com.example.ombreapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnPGg5yh2oyY5vn8RarfhzTEP26ETlfUw',
    appId: '1:602344830112:ios:0e22e7c696435cb14ec5c5',
    messagingSenderId: '602344830112',
    projectId: 'ombre-event-6d20c',
    storageBucket: 'ombre-event-6d20c.appspot.com',
    iosClientId:
        '602344830112-k9f86lmvinml06t598u6lpgi5khfpj61.apps.googleusercontent.com',
    iosBundleId: 'com.example.ombreapp',
  );
}
